{"street_address": "3216-25 Richmond Street E", "city": "Toronto", "province": "ON", "neighbourhood": "Church-Yonge Corridor", "price": "899999", "bed": "2+2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": "0-5 Years Old"}
{"street_address": "5 Sabrina Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Willowridge-Martingrove-Richview", "price": "1148868", "bed": "3+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "66 Stapleton Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Kingsview Village-The Westway", "price": "1299000", "bed": "3 bed", "bath": "2 bath", "sqft": "1500-2000 sqft", "age": null}
{"street_address": "31 Moorecroft Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "Ionview", "price": "999000", "bed": "3+2 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "PH1204-35 Fontenay Court", "city": "Toronto", "province": "ON", "neighbourhood": "Edenbridge-Humber Valley", "price": "979000", "bed": "2+1 bed", "bath": "2 bath", "sqft": "1000-1199 sqft", "age": null}
{"street_address": "101-120 Canon Jackson Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Brookhaven-Amesbury", "price": "499999", "bed": "1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "New"}
{"street_address": "#502-40 Bay Mills Boulevard", "city": "Toronto", "province": "ON", "neighbourhood": "Tam O'Shanter-Sullivan", "price": "519900", "bed": "2 bed", "bath": "1 bath", "sqft": "900-999 sqft", "age": null}
{"street_address": "2608-8 Park Road", "city": "Toronto", "province": "ON", "neighbourhood": "Rosedale-Moore Park", "price": "630000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "16-30 Years Old"}
{"street_address": "166 Harvie Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Corso Italia-Davenport", "price": "998888", "bed": "2+1 bed", "bath": "2 bath", "sqft": "1500-2000 sqft", "age": null}
{"street_address": "1219 Brimley Road", "city": "Toronto", "province": "ON", "neighbourhood": "Bendale", "price": "899900", "bed": "3+1 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "17 Leona Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Willowdale East", "price": "2898898", "bed": "4+1 bed", "bath": "4 bath", "sqft": null, "age": null}
{"street_address": " Caravan Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Banbury-Don Mills", "price": null, "bed": "$X,XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "12-66 Long Branch Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Long Branch", "price": "1125000", "bed": "2 bed", "bath": "3 bath", "sqft": "1400-1599 sqft", "age": null}
{"street_address": "2603-161 Roehampton Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Mount Pleasant West", "price": "769900", "bed": "2 bed", "bath": "2 bath", "sqft": "600-699 sqft", "age": "0-5 Years Old"}
{"street_address": "302-8 Wellesley Street E", "city": "Toronto", "province": "ON", "neighbourhood": "Church-Yonge Corridor", "price": "750000", "bed": "2 bed", "bath": "2 bath", "sqft": "1000-1199 sqft", "age": null}
{"street_address": "1210-325 Bay Street", "city": "Toronto", "province": "ON", "neighbourhood": "Bay Street Corridor", "price": "1200000", "bed": "1 bed", "bath": "1 bath", "sqft": "900-999 sqft", "age": null}
{"street_address": "3 Minnie Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Downsview-Roding-CFB", "price": "1039000", "bed": "4 bed", "bath": "2 bath", "sqft": "51-99 Years Old", "age": null}
{"street_address": "15 Hamstead Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Woodbine-Lumsden", "price": "1699999", "bed": "3 bed", "bath": "3 bath", "sqft": "1500-2000 sqft", "age": null}
{"street_address": "6 Lisburn Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "Don Valley Village", "price": "999900", "bed": "3 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "1-70 Orchid Place Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Malvern", "price": "399000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "0-5 Years Old"}
{"street_address": "401-1387 Bayview Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Leaside", "price": "875000", "bed": "2 bed", "bath": "2 bath", "sqft": "1200-1399 sqft", "age": "16-30 Years Old"}
{"street_address": "309-18 Kenaston Gardens", "city": "Toronto", "province": "ON", "neighbourhood": "Bayview Village", "price": "639900", "bed": "1+1 bed", "bath": "2 bath", "sqft": "600-699 sqft", "age": "16-30 Years Old"}
{"street_address": "207-1369 Bloor Street W", "city": "Toronto", "province": "ON", "neighbourhood": "Dufferin Grove", "price": "629000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "191 Rustic Road", "city": "Toronto", "province": "ON", "neighbourhood": "Rustic", "price": "1648888", "bed": "4+1 bed", "bath": "3 bath", "sqft": "2000-2500 sqft", "age": null}
{"street_address": "99 Parklea Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Leaside", "price": "2295000", "bed": "3+1 bed", "bath": "4 bath", "sqft": null, "age": null}
{"street_address": "311-25 Neighbourhood Lane", "city": "Toronto", "province": "ON", "neighbourhood": "Stonegate-Queensway", "price": "549900", "bed": "1+1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "New"}
{"street_address": "1003-25 Neighbourhood Lane", "city": "Toronto", "province": "ON", "neighbourhood": "Stonegate-Queensway", "price": "1199900", "bed": "3+1 bed", "bath": "2 bath", "sqft": "1200-1399 sqft", "age": "New"}
{"street_address": "710-25 Neighbourhood Lane", "city": "Toronto", "province": "ON", "neighbourhood": "Stonegate-Queensway", "price": "559900", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "New"}
{"street_address": "811-25 Neighbourhood Lane", "city": "Toronto", "province": "ON", "neighbourhood": "Stonegate-Queensway", "price": "589900", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "New"}
{"street_address": "1005-25 Neighbourhood Lane", "city": "Toronto", "province": "ON", "neighbourhood": "Stonegate-Queensway", "price": "949900", "bed": "2+1 bed", "bath": "2 bath", "sqft": "900-999 sqft", "age": "New"}
{"street_address": "1012-25 Neighbourhood Lane", "city": "Toronto", "province": "ON", "neighbourhood": "Stonegate-Queensway", "price": "769900", "bed": "2+1 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": "New"}
{"street_address": "402-1387 Bayview Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Leaside", "price": "649900", "bed": "2 bed", "bath": "2 bath", "sqft": "1000-1199 sqft", "age": "16-30 Years Old"}
{"street_address": "704-4 Park Vista ", "city": "Toronto", "province": "ON", "neighbourhood": "O'Connor-Parkview", "price": "449900", "bed": "1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": "31-50 Years Old"}
{"street_address": "211 Calvington Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Downsview-Roding-CFB", "price": "1359999", "bed": "3+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "4 Westlake Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "Woodbine-Lumsden", "price": "799000", "bed": "3+2 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "1309-1420 Dupont Street", "city": "Toronto", "province": "ON", "neighbourhood": "Dovercourt-Wallace Emerson-Junction", "price": "489000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": null}
{"street_address": "1110NT-99 Broadway Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Mount Pleasant West", "price": "770000", "bed": "2 bed", "bath": "2 bath", "sqft": "600-699 sqft", "age": "0-5 Years Old"}
{"street_address": "1107-576 Front Street W", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "1225000", "bed": "2 bed", "bath": "2 bath", "sqft": "900-999 sqft", "age": "0-5 Years Old"}
{"street_address": "32 Wolfrey Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "North Riverdale", "price": "999000", "bed": "2+1 bed", "bath": "2 bath", "sqft": "1100-1500 sqft", "age": "100+ Years Old"}
{"street_address": "52 Hunting Ridge", "city": "Toronto", "province": "ON", "neighbourhood": "Willowridge-Martingrove-Richview", "price": "1599900", "bed": "3+1 bed", "bath": "3 bath", "sqft": "51-99 Years Old", "age": null}
{"street_address": "159 Brentwood Road N", "city": "Toronto", "province": "ON", "neighbourhood": "Kingsway South", "price": "3850000", "bed": "4+1 bed", "bath": "7 bath", "sqft": "0-5 Years Old", "age": null}
{"street_address": "162 Virginia Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Danforth Village-East York", "price": "1098000", "bed": "4 bed", "bath": "3 bath", "sqft": "1500-2000 sqft", "age": null}
{"street_address": "215 Cocksfield Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Bathurst Manor", "price": "1499000", "bed": "4+1 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "24-100 Bartley Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Victoria Village", "price": "1175000", "bed": "4+1 bed", "bath": "4 bath", "sqft": "1500-2000 sqft", "age": "New"}
{"street_address": "3106-5180 Yonge Street", "city": "Toronto", "province": "ON", "neighbourhood": "Willowdale West", "price": "948800", "bed": "2+1 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": "0-5 Years Old"}
{"street_address": "209-72 Esther Shiner Boulevard", "city": "Toronto", "province": "ON", "neighbourhood": "Bayview Village", "price": "648998", "bed": "1+1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "315-30 Roehampton Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Mount Pleasant West", "price": "829000", "bed": "2+1 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": "6-10 Years Old"}
{"street_address": "108-7 Thornwood Road", "city": "Toronto", "province": "ON", "neighbourhood": "Rosedale-Moore Park", "price": "1449900", "bed": "2 bed", "bath": "2 bath", "sqft": "1200-1399 sqft", "age": null}
{"street_address": "41 Cree Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Cliffcrest", "price": "998800", "bed": "2+1 bed", "bath": "1 bath", "sqft": null, "age": null}
{"street_address": "439-1830 Bloor Street W", "city": "Toronto", "province": "ON", "neighbourhood": "High Park North", "price": "489000", "bed": "– bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": null}
{"street_address": "45-2 Dailing Gate", "city": "Toronto", "province": "ON", "neighbourhood": "Malvern", "price": "668800", "bed": "3+1 bed", "bath": "2 bath", "sqft": "1400-1599 sqft", "age": null}
{"street_address": "S325-455 Front Street E", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C8", "price": "649000", "bed": "1+1 bed", "bath": "2 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "1510-5765 Yonge Street", "city": "Toronto", "province": "ON", "neighbourhood": "Newtonbrook East", "price": "729900", "bed": "2+1 bed", "bath": "2 bath", "sqft": "1000-1199 sqft", "age": null}
{"street_address": "525-99 The Donway West ", "city": "Toronto", "province": "ON", "neighbourhood": "Banbury-Don Mills", "price": "649000", "bed": "1+1 bed", "bath": "2 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "3306-125 Peter Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "709000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "6-10 Years Old"}
{"street_address": "2203-18 Graydon Hall Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Parkwoods-Donalda", "price": "759000", "bed": "2 bed", "bath": "2 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "504-21 Grand Magazine Street", "city": "Toronto", "province": "ON", "neighbourhood": "Niagara", "price": "768888", "bed": "1+1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "1112 Greenwood Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "East York", "price": "1080000", "bed": "2+2 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "134 Upper Canada Drive", "city": "Toronto", "province": "ON", "neighbourhood": "St. Andrew-Windfields", "price": "1799900", "bed": "2+1 bed", "bath": "1 bath", "sqft": "700-1100 sqft", "age": null}
{"street_address": "15-1666 Queen Street E", "city": "Toronto", "province": "ON", "neighbourhood": "Woodbine Corridor", "price": "799000", "bed": "3 bed", "bath": "1 bath", "sqft": "1200-1399 sqft", "age": "31-50 Years Old"}
{"street_address": "204-355 Bedford Park Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Bedford Park-Nortown", "price": "1279000", "bed": "2 bed", "bath": "2 bath", "sqft": "1000-1199 sqft", "age": "0-5 Years Old"}
{"street_address": "1901-35 Balmuto Street", "city": "Toronto", "province": "ON", "neighbourhood": "Bay Street Corridor", "price": "799000", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": "82 Wayland Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "East End-Danforth", "price": "1388000", "bed": "4+1 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "57 Castle Frank Road", "city": "Toronto", "province": "ON", "neighbourhood": "Rosedale-Moore Park", "price": "3999000", "bed": "5 bed", "bath": "4 bath", "sqft": null, "age": null}
{"street_address": "821-80 Harrison Garden Boulevard", "city": "Toronto", "province": "ON", "neighbourhood": "Willowdale East", "price": "599000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": "4 Nightingale Place", "city": "Toronto", "province": "ON", "neighbourhood": "Woburn", "price": "999000", "bed": "3 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "2010-812 Burnhamthorpe Road", "city": "Toronto", "province": "ON", "neighbourhood": "Markland Wood", "price": "819980", "bed": "3 bed", "bath": "2 bath", "sqft": "1200-1399 sqft", "age": "31-50 Years Old"}
{"street_address": "67 Edward Norton Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "Islington-City Centre West", "price": "1269000", "bed": "3+1 bed", "bath": "3 bath", "sqft": "1600-1799 sqft", "age": "6-10 Years Old"}
{"street_address": "1334-5 Mabelle Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Islington-City Centre West", "price": "569990", "bed": "1+1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "0-5 Years Old"}
{"street_address": "104-15 Strangford Lane", "city": "Toronto", "province": "ON", "neighbourhood": "Clairlea-Birchmount", "price": "749900", "bed": "2+1 bed", "bath": "2 bath", "sqft": "1200-1399 sqft", "age": "16-30 Years Old"}
{"street_address": "1215E-36 Lisgar Street", "city": "Toronto", "province": "ON", "neighbourhood": "Little Portugal", "price": "598500", "bed": "1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "2922-585 Bloor Street E", "city": "Toronto", "province": "ON", "neighbourhood": "North St. James Town", "price": "988000", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": "0-5 Years Old"}
{"street_address": "2615-70 Temperance Street", "city": "Toronto", "province": "ON", "neighbourhood": "Bay Street Corridor", "price": "899000", "bed": "2 bed", "bath": "2 bath", "sqft": "700-799 sqft", "age": "6-10 Years Old"}
{"street_address": "103-207 Wellesley Street E", "city": "Toronto", "province": "ON", "neighbourhood": "Cabbagetown-South St. James Town", "price": "749900", "bed": "2+1 bed", "bath": "2 bath", "sqft": "900-999 sqft", "age": null}
{"street_address": "395 Markland Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Markland Wood", "price": "2698000", "bed": "5 bed", "bath": "6 bath", "sqft": "5000+ sqft", "age": null}
{"street_address": "40 Beresford Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "High Park-Swansea", "price": "3098000", "bed": "3+1 bed", "bath": "5 bath", "sqft": null, "age": null}
{"street_address": "535 Strathmore Boulevard", "city": "Toronto", "province": "ON", "neighbourhood": "Danforth", "price": "1149000", "bed": "3+1 bed", "bath": "3 bath", "sqft": "1500-2000 sqft", "age": null}
{"street_address": "120 Kingston Road", "city": "Toronto", "province": "ON", "neighbourhood": "The Beaches", "price": "1189000", "bed": "3 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "114 Bertrand Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Ionview", "price": "1099000", "bed": "3+1 bed", "bath": "3 bath", "sqft": "1100-1500 sqft", "age": "51-99 Years Old"}
{"street_address": "2505-1410 Dupont Street", "city": "Toronto", "province": "ON", "neighbourhood": "Dovercourt-Wallace Emerson-Junction", "price": "578000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "311-293 The Kingsway ", "city": "Toronto", "province": "ON", "neighbourhood": "Edenbridge-Humber Valley", "price": "628000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "0-5 Years Old"}
{"street_address": "220-10 Eddystone Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Glenfield-Jane Heights", "price": "395000", "bed": "3 bed", "bath": "2 bath", "sqft": "1000-1199 sqft", "age": null}
{"street_address": "TH-14-60 Orchid Place Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Malvern", "price": "389900", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "0-5 Years Old"}
{"street_address": "1906-28 Wellesley Street E", "city": "Toronto", "province": "ON", "neighbourhood": "Church-Yonge Corridor", "price": "588000", "bed": "1 bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": null}
{"street_address": "735-525 Adelaide Street W", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "699900", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "641-38 Western Battery Road", "city": "Toronto", "province": "ON", "neighbourhood": "Niagara", "price": "799900", "bed": "1+1 bed", "bath": "1 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": " Wellington Street W", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": null, "bed": "$X,XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "148 Silverthorn Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Weston-Pellam Park", "price": "899898", "bed": "2+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "2 Rosemarie Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Wexford-Maryvale", "price": "1088898", "bed": "3+1 bed", "bath": "2 bath", "sqft": "700-1100 sqft", "age": "51-99 Years Old"}
{"street_address": "46 High Hill Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Tam O'Shanter-Sullivan", "price": "1100000", "bed": "4 bed", "bath": "2 bath", "sqft": "51-99 Years Old", "age": null}
{"street_address": "3906-1926 Lake Shore Boulevard W", "city": "Toronto", "province": "ON", "neighbourhood": "High Park-Swansea", "price": "1175000", "bed": "2 bed", "bath": "2 bath", "sqft": "900-999 sqft", "age": "0-5 Years Old"}
{"street_address": "101-100 Canon Jackson Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Beechborough-Greenbrook", "price": "699000", "bed": "2 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": "0-5 Years Old"}
{"street_address": "303A-88 Corporate Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Woburn", "price": "639900", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": "501-45 Dovercourt Road", "city": "Toronto", "province": "ON", "neighbourhood": "Trinity-Bellwoods", "price": "1699000", "bed": "2 bed", "bath": "3 bath", "sqft": "1400-1599 sqft", "age": null}
{"street_address": "202-260 Merton Street", "city": "Toronto", "province": "ON", "neighbourhood": "Mount Pleasant West", "price": "645000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": "16-30 Years Old"}
{"street_address": "204-135 Maitland Street", "city": "Toronto", "province": "ON", "neighbourhood": "Church-Yonge Corridor", "price": "550000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "16-30 Years Old"}
{"street_address": "PH02-915 King Street W", "city": "Toronto", "province": "ON", "neighbourhood": "Niagara", "price": "949000", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": "323 Dalesford Road", "city": "Toronto", "province": "ON", "neighbourhood": "Stonegate-Queensway", "price": "1199900", "bed": "3 bed", "bath": "2 bath", "sqft": "2000-2500 sqft", "age": null}
{"street_address": "74 Derrydown Road W", "city": "Toronto", "province": "ON", "neighbourhood": "York University Heights", "price": "1199000", "bed": "3 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "2 Royal Doulton Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Parkwoods-Donalda", "price": "1628000", "bed": "3 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "619-120 Harrison Garden Boulevard", "city": "Toronto", "province": "ON", "neighbourhood": "Willowdale East", "price": "675000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "3010-373 Front Street W", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "699900", "bed": "1+1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "28 Glenorchy Road", "city": "Toronto", "province": "ON", "neighbourhood": "Bridle Path-Sunnybrook-York Mills", "price": "10980000", "bed": "4+2 bed", "bath": "7 bath", "sqft": "5000+ sqft", "age": null}
{"street_address": "550 Cranbrooke Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Bedford Park-Nortown", "price": "3579000", "bed": "4+1 bed", "bath": "5 bath", "sqft": null, "age": null}
{"street_address": "3409-105 The Queensway ", "city": "Toronto", "province": "ON", "neighbourhood": "High Park-Swansea", "price": "499000", "bed": "1 bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": null}
{"street_address": "19 Leahann Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Dorset Park", "price": "999000", "bed": "3+2 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "28 Winnifred Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "South Riverdale", "price": "1489000", "bed": "3+1 bed", "bath": "4 bath", "sqft": null, "age": null}
{"street_address": "29 Hillary Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Keelesdale-Eglinton West", "price": "1149000", "bed": "3 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "30 Nursewood Road", "city": "Toronto", "province": "ON", "neighbourhood": "The Beaches", "price": "1699000", "bed": "3+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "56 Greenwood Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Greenwood-Coxwell", "price": "1199000", "bed": "3 bed", "bath": "3 bath", "sqft": "51-99 Years Old", "age": null}
{"street_address": "805-38 William Carson Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "St. Andrew-Windfields", "price": "2188000", "bed": "3 bed", "bath": "3 bath", "sqft": "1600-1799 sqft", "age": null}
{"street_address": "19 Moraine Hill Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Tam O'Shanter-Sullivan", "price": "1088800", "bed": "3+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "15 Tanburn Place", "city": "Toronto", "province": "ON", "neighbourhood": "Parkwoods-Donalda", "price": "2150000", "bed": "4 bed", "bath": "5 bath", "sqft": null, "age": null}
{"street_address": "813-158 Front Street E", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C8", "price": "850000", "bed": "2 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": "0-5 Years Old"}
{"street_address": "TH3-15 Greenview Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Newtonbrook West", "price": "1299000", "bed": "3 bed", "bath": "3 bath", "sqft": "1800-1999 sqft", "age": "16-30 Years Old"}
{"street_address": "521-72 Esther Shiner Boulevard", "city": "Toronto", "province": "ON", "neighbourhood": "Bayview Village", "price": "499000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "0-5 Years Old"}
{"street_address": "18-1597 Bathurst Street", "city": "Toronto", "province": "ON", "neighbourhood": "Forest Hill South", "price": "699900", "bed": "3+1 bed", "bath": "1 bath", "sqft": "1200-1399 sqft", "age": "100+ Years Old"}
{"street_address": "54 Preston Street", "city": "Toronto", "province": "ON", "neighbourhood": "Birchcliffe-Cliffside", "price": "799900", "bed": "3 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "2112-5180 Yonge Street", "city": "Toronto", "province": "ON", "neighbourhood": "Willowdale West", "price": "828888", "bed": "2 bed", "bath": "2 bath", "sqft": "700-799 sqft", "age": "0-5 Years Old"}
{"street_address": "2603-9 Bogert Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Lansing-Westgate", "price": "969000", "bed": "2+1 bed", "bath": "2 bath", "sqft": "900-999 sqft", "age": "6-10 Years Old"}
{"street_address": "1007-70 Temperance Street", "city": "Toronto", "province": "ON", "neighbourhood": "Bay Street Corridor", "price": "599000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "6-10 Years Old"}
{"street_address": "421-21 Clairtrell Road N", "city": "Toronto", "province": "ON", "neighbourhood": "Willowdale East", "price": "868888", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": "806-88 Alton Towers Circle", "city": "Toronto", "province": "ON", "neighbourhood": "Milliken", "price": "555000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "102-365 Dundas Street E", "city": "Toronto", "province": "ON", "neighbourhood": "Moss Park", "price": "630000", "bed": "1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "3105-5180 Yonge Street", "city": "Toronto", "province": "ON", "neighbourhood": "Willowdale West", "price": "769000", "bed": "2 bed", "bath": "2 bath", "sqft": "700-799 sqft", "age": "0-5 Years Old"}
{"street_address": "18 Palamar Road", "city": "Toronto", "province": "ON", "neighbourhood": "Downsview-Roding-CFB", "price": "1465000", "bed": "3+2 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "15 Rubicon Court", "city": "Toronto", "province": "ON", "neighbourhood": "Newtonbrook East", "price": "2088000", "bed": "4 bed", "bath": "5 bath", "sqft": null, "age": null}
{"street_address": "1205-1190 Dundas Street E", "city": "Toronto", "province": "ON", "neighbourhood": "South Riverdale", "price": "675000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "6-10 Years Old"}
{"street_address": " Bloorview Place", "city": "Toronto", "province": "ON", "neighbourhood": "Don Valley Village", "price": null, "bed": "$XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "2809-8 Charlotte Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "729000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "87-760 Lawrence Avenue W", "city": "Toronto", "province": "ON", "neighbourhood": "Yorkdale-Glen Park", "price": "799000", "bed": "2+1 bed", "bath": "3 bath", "sqft": "1000-1199 sqft", "age": null}
{"street_address": "906-5580 Sheppard Avenue E", "city": "Toronto", "province": "ON", "neighbourhood": "Malvern", "price": "550000", "bed": "2 bed", "bath": "1 bath", "sqft": "800-899 sqft", "age": "31-50 Years Old"}
{"street_address": "PARKING-35 Mariner Terrace", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "49000", "bed": "– bed", "bath": "– bath", "sqft": "0-499 sqft", "age": "0-5 Years Old"}
{"street_address": "8 Aikenhead Road", "city": "Toronto", "province": "ON", "neighbourhood": "Kingsview Village-The Westway", "price": "888888", "bed": "3+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "3208-20 Shore Breeze Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Mimico", "price": "775000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "0-5 Years Old"}
{"street_address": "515-1881 Mcnicoll Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Steeles", "price": "799900", "bed": "3 bed", "bath": "3 bath", "sqft": "1400-1599 sqft", "age": "16-30 Years Old"}
{"street_address": "2507-30 Gibbs Road", "city": "Toronto", "province": "ON", "neighbourhood": "Islington-City Centre West", "price": "769000", "bed": "3 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": "12 Tait Court", "city": "Toronto", "province": "ON", "neighbourhood": "Rouge E11", "price": "929999", "bed": "4 bed", "bath": "4 bath", "sqft": null, "age": null}
{"street_address": "202-225 Sherway Gardens Road", "city": "Toronto", "province": "ON", "neighbourhood": "Islington-City Centre West", "price": "550000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "303-90 Queens Wharf Road", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "959000", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": "1414-2885 Bayview Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Bayview Village", "price": "599900", "bed": "1+1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": "6-10 Years Old"}
{"street_address": "12 Kipping Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Weston-Pellam Park", "price": "1220000", "bed": "3 bed", "bath": "2 bath", "sqft": "1100-1500 sqft", "age": "0-5 Years Old"}
{"street_address": "812-90 Ling Road", "city": "Toronto", "province": "ON", "neighbourhood": "West Hill", "price": "488000", "bed": "2 bed", "bath": "1 bath", "sqft": "1000-1199 sqft", "age": null}
{"street_address": "302-293 The Kingsway ", "city": "Toronto", "province": "ON", "neighbourhood": "Edenbridge-Humber Valley", "price": "1195000", "bed": "2+1 bed", "bath": "3 bath", "sqft": "900-999 sqft", "age": null}
{"street_address": "4804-311 Bay Street", "city": "Toronto", "province": "ON", "neighbourhood": "Bay Street Corridor", "price": "1980000", "bed": "2 bed", "bath": "2 bath", "sqft": "1800-1999 sqft", "age": null}
{"street_address": "41 Pitfifled Road S", "city": "Toronto", "province": "ON", "neighbourhood": "Agincourt South-Malvern West", "price": "930000", "bed": "4+1 bed", "bath": "3 bath", "sqft": "31-50 Years Old", "age": null}
{"street_address": "608-70 Annie Craig Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Mimico", "price": "669900", "bed": "1+1 bed", "bath": "2 bath", "sqft": "600-699 sqft", "age": "0-5 Years Old"}
{"street_address": "211-70 Cass Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Tam O'Shanter-Sullivan", "price": "649000", "bed": "3 bed", "bath": "2 bath", "sqft": "1200-1399 sqft", "age": null}
{"street_address": "1601-130 River Street", "city": "Toronto", "province": "ON", "neighbourhood": "Regent Park", "price": "745900", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "0-5 Years Old"}
{"street_address": " Strathgowan Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Lawrence Park South", "price": null, "bed": "$X,XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "S901-180 Mill Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C8", "price": "649900", "bed": "1+1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "New"}
{"street_address": "221 Beta Street", "city": "Toronto", "province": "ON", "neighbourhood": "Alderwood", "price": "1929900", "bed": "3 bed", "bath": "4 bath", "sqft": "2000-2500 sqft", "age": null}
{"street_address": "105-293 The Kingsway Way S", "city": "Toronto", "province": "ON", "neighbourhood": "Edenbridge-Humber Valley", "price": "839000", "bed": "2+2 bed", "bath": "2 bath", "sqft": "700-799 sqft", "age": "New"}
{"street_address": "1912-121 Mcmahon Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Bayview Village", "price": "579000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "0-5 Years Old"}
{"street_address": "4010-161 Roehampton Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Mount Pleasant West", "price": "725000", "bed": "1+1 bed", "bath": "2 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "1311-120 Harrison Garden Boulevard", "city": "Toronto", "province": "ON", "neighbourhood": "Willowdale East", "price": "699900", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "6-10 Years Old"}
{"street_address": "N2404-5915 Yonge Street", "city": "Toronto", "province": "ON", "neighbourhood": "Newtonbrook East", "price": "929000", "bed": "2+1 bed", "bath": "2 bath", "sqft": "900-999 sqft", "age": "New"}
{"street_address": "3 Ridgewood Road", "city": "Toronto", "province": "ON", "neighbourhood": "Forest Hill South", "price": "4480000", "bed": "4 bed", "bath": "6 bath", "sqft": "3500-5000 sqft", "age": "51-99 Years Old"}
{"street_address": "1608-400 Mclevin Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Malvern", "price": "584900", "bed": "2 bed", "bath": "2 bath", "sqft": "1200-1399 sqft", "age": null}
{"street_address": "3 Garden Circle", "city": "Toronto", "province": "ON", "neighbourhood": "Leaside", "price": "5950000", "bed": "4 bed", "bath": "6 bath", "sqft": null, "age": null}
{"street_address": "TH116-107 The Queensway ", "city": "Toronto", "province": "ON", "neighbourhood": "High Park-Swansea", "price": "1488888", "bed": "3 bed", "bath": "3 bath", "sqft": "1600-1799 sqft", "age": "16-30 Years Old"}
{"street_address": "117-360 Ridelle Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Briar Hill-Belgravia", "price": "485000", "bed": "1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "53-2075 Warden Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Tam O'Shanter-Sullivan", "price": "899999", "bed": "4+1 bed", "bath": "2 bath", "sqft": "1200-1399 sqft", "age": "31-50 Years Old"}
{"street_address": "22 Wallingford Road", "city": "Toronto", "province": "ON", "neighbourhood": "Parkwoods-Donalda", "price": "1515000", "bed": "3+2 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "3003-89 Mcgill Street", "city": "Toronto", "province": "ON", "neighbourhood": "Church-Yonge Corridor", "price": "609900", "bed": "1 bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": "0-5 Years Old"}
{"street_address": "46 Dingwall Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Blake-Jones", "price": "1595000", "bed": "4 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "166 Moore Park Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Newtonbrook West", "price": "1660000", "bed": "3 bed", "bath": "2 bath", "sqft": "51-99 Years Old", "age": null}
{"street_address": "1305-38 Joe Shuster Way", "city": "Toronto", "province": "ON", "neighbourhood": "South Parkdale", "price": "640000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "613-90 Broadview Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "South Riverdale", "price": "519000", "bed": "1 bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": "6-10 Years Old"}
{"street_address": "1819-251 Jarvis Street", "city": "Toronto", "province": "ON", "neighbourhood": "Church-Yonge Corridor", "price": "399888", "bed": "– bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": "0-5 Years Old"}
{"street_address": "2213-10 Queens Quay W", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "788800", "bed": "1+1 bed", "bath": "2 bath", "sqft": "900-999 sqft", "age": null}
{"street_address": "108 Melville Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Dovercourt-Wallace Emerson-Junction", "price": "1320000", "bed": "4+2 bed", "bath": "4 bath", "sqft": null, "age": null}
{"street_address": "903-30 Thunder Grove", "city": "Toronto", "province": "ON", "neighbourhood": "Agincourt North", "price": "499000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "76-10 Cardwell Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Agincourt South-Malvern West", "price": "899000", "bed": "3 bed", "bath": "3 bath", "sqft": "1600-1799 sqft", "age": null}
{"street_address": "76-10 Cardwell Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Agincourt South-Malvern West", "price": "899000", "bed": "3 bed", "bath": "3 bath", "sqft": "1600-1799 sqft", "age": null}
{"street_address": "1802-38 Dan Leckie Way", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "549000", "bed": "1 bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": null}
{"street_address": "1903-88 Cumberland Road N", "city": "Toronto", "province": "ON", "neighbourhood": "Annex", "price": "950000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": null}
{"street_address": "84 Gristone Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "Rouge E11", "price": "875000", "bed": "3 bed", "bath": "2 bath", "sqft": "1100-1500 sqft", "age": "16-30 Years Old"}
{"street_address": "107 Bowood Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Lawrence Park North", "price": "1789000", "bed": "3 bed", "bath": "4 bath", "sqft": "2000-2500 sqft", "age": "31-50 Years Old"}
{"street_address": "32 Pont Lane", "city": "Toronto", "province": "ON", "neighbourhood": "Weston", "price": "938000", "bed": "3+1 bed", "bath": "2 bath", "sqft": "1500-2000 sqft", "age": null}
{"street_address": "42 Agar Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "Islington-City Centre West", "price": "3499000", "bed": "4+1 bed", "bath": "5 bath", "sqft": null, "age": null}
{"street_address": "157 Brockley Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Bendale", "price": "1339990", "bed": "4 bed", "bath": "4 bath", "sqft": "1500-2000 sqft", "age": "New"}
{"street_address": "272 Cranbrooke Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Lawrence Park North", "price": "3749000", "bed": "4+1 bed", "bath": "5 bath", "sqft": "3500-5000 sqft", "age": "0-5 Years Old"}
{"street_address": "43 Winnett Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Humewood-Cedarvale", "price": "1379000", "bed": "3+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "52 Vernon Street", "city": "Toronto", "province": "ON", "neighbourhood": "Junction Area", "price": "999000", "bed": "2 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "522-230 King Street E", "city": "Toronto", "province": "ON", "neighbourhood": "Moss Park", "price": "738000", "bed": "2 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": " Roslin Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Lawrence Park North", "price": null, "bed": "$X,XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "5 Braemar Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Yonge-Eglinton", "price": "3580000", "bed": "3+2 bed", "bath": "4 bath", "sqft": "3000-3500 sqft", "age": null}
{"street_address": "242 Westmount Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Oakwood Village", "price": "849900", "bed": "2+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "110-1183 Dufferin Street", "city": "Toronto", "province": "ON", "neighbourhood": "Dovercourt-Wallace Emerson-Junction", "price": "599000", "bed": "1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "725-75 Portland Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "599000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "11-15 Years Old"}
{"street_address": "25 Falstaff Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Maple Leaf", "price": "1100000", "bed": "3+1 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "71 Northdale Boulevard", "city": "Toronto", "province": "ON", "neighbourhood": "O'Connor-Parkview", "price": "1288000", "bed": "4 bed", "bath": "4 bath", "sqft": "1500-2000 sqft", "age": null}
{"street_address": "26 Woodfield Road", "city": "Toronto", "province": "ON", "neighbourhood": "Greenwood-Coxwell", "price": "1749000", "bed": "4+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "112-1183 Dufferin Street", "city": "Toronto", "province": "ON", "neighbourhood": "Dovercourt-Wallace Emerson-Junction", "price": "760000", "bed": "2+1 bed", "bath": "3 bath", "sqft": "1000-1199 sqft", "age": null}
{"street_address": "78-121 Centennial Road", "city": "Toronto", "province": "ON", "neighbourhood": "Centennial Scarborough", "price": "648000", "bed": "3 bed", "bath": "2 bath", "sqft": "1200-1399 sqft", "age": null}
{"street_address": "1037-251 Jarvis Street N", "city": "Toronto", "province": "ON", "neighbourhood": "Church-Yonge Corridor", "price": "539999", "bed": "1 bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": "0-5 Years Old"}
{"street_address": "710-78 Harrison Garden Boulevard", "city": "Toronto", "province": "ON", "neighbourhood": "Willowdale East", "price": "789000", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": "702-501 Adelaide Street W", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "1198000", "bed": "2 bed", "bath": "2 bath", "sqft": "1000-1199 sqft", "age": "0-5 Years Old"}
{"street_address": " Davenport Road", "city": "Toronto", "province": "ON", "neighbourhood": "Annex", "price": null, "bed": "$X,XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "1212-170 Sumach Street", "city": "Toronto", "province": "ON", "neighbourhood": "Regent Park", "price": "659000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "55 Abbott Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "High Park North", "price": "999000", "bed": "3 bed", "bath": "1 bath", "sqft": null, "age": null}
{"street_address": "67 Montressor Drive", "city": "Toronto", "province": "ON", "neighbourhood": "St. Andrew-Windfields", "price": "6490000", "bed": "5+1 bed", "bath": "7 bath", "sqft": "5000+ sqft", "age": "New"}
{"street_address": "310-4005 Don Mills Road", "city": "Toronto", "province": "ON", "neighbourhood": "Hillcrest Village", "price": "792000", "bed": "4 bed", "bath": "3 bath", "sqft": "1200-1399 sqft", "age": "31-50 Years Old"}
{"street_address": " George Street", "city": "Toronto", "province": "ON", "neighbourhood": "Moss Park", "price": null, "bed": "$XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "562 Beresford Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Runnymede-Bloor West Village", "price": "1998000", "bed": "3+2 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "7 Lark Street", "city": "Toronto", "province": "ON", "neighbourhood": "The Beaches", "price": "1299000", "bed": "3+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": " Broadway Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Mount Pleasant East", "price": null, "bed": "$X,XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "179 Rosewell Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Lawrence Park South", "price": "1699000", "bed": "4 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "9H-6 Rosebank Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Malvern", "price": "499000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "2606-170 Bayview Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C8", "price": "599000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "0-5 Years Old"}
{"street_address": "1606-68 Abell Street", "city": "Toronto", "province": "ON", "neighbourhood": "Little Portugal", "price": "699000", "bed": "2 bed", "bath": "2 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "1004-1105 Leslie Street", "city": "Toronto", "province": "ON", "neighbourhood": "Banbury-Don Mills", "price": "708000", "bed": "2 bed", "bath": "2 bath", "sqft": "900-999 sqft", "age": "16-30 Years Old"}
{"street_address": "49 Culnan Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Islington-City Centre West", "price": "988000", "bed": "2+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "220-816 Lansdowne Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Dovercourt-Wallace Emerson-Junction", "price": "564900", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "1709-370 Dixon Road", "city": "Toronto", "province": "ON", "neighbourhood": "Kingsview Village-The Westway", "price": "469000", "bed": "2 bed", "bath": "1 bath", "sqft": "1000-1199 sqft", "age": "51-99 Years Old"}
{"street_address": "1301-125 Peter Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "959900", "bed": "3 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": "6-10 Years Old"}
{"street_address": "10 Chiltern Hill Road", "city": "Toronto", "province": "ON", "neighbourhood": "Humewood-Cedarvale", "price": "4199000", "bed": "4+1 bed", "bath": "5 bath", "sqft": null, "age": null}
{"street_address": "370 Hillsdale Avenue E", "city": "Toronto", "province": "ON", "neighbourhood": "Mount Pleasant East", "price": "2775000", "bed": "4+1 bed", "bath": "5 bath", "sqft": "0-5 Years Old", "age": null}
{"street_address": "2 Del Ria Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Maple Leaf", "price": "999000", "bed": "3 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "561 Arlington Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Humewood-Cedarvale", "price": "2650000", "bed": "3 bed", "bath": "4 bath", "sqft": null, "age": null}
{"street_address": "803-608 Richmond Street W", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "499000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "0-5 Years Old"}
{"street_address": "89 Twenty Fourth Street", "city": "Toronto", "province": "ON", "neighbourhood": "Long Branch", "price": "999000", "bed": "3+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "717 Coxwell Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Danforth", "price": "1225000", "bed": "Office", "bath": "2400 sqft", "sqft": null, "age": null}
{"street_address": "28-715 Lawrence Avenue W", "city": "Toronto", "province": "ON", "neighbourhood": "Yorkdale-Glen Park", "price": "799999", "bed": "2 bed", "bath": "2 bath", "sqft": "900-999 sqft", "age": "0-5 Years Old"}
{"street_address": "109-580 Kingston Road", "city": "Toronto", "province": "ON", "neighbourhood": "The Beaches", "price": "1099000", "bed": "3+1 bed", "bath": "2 bath", "sqft": "1200-1399 sqft", "age": "6-10 Years Old"}
{"street_address": "10-14 York Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "669800", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "6-10 Years Old"}
{"street_address": "1602-25 Mcmahon Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Bayview Village", "price": "1506900", "bed": "3 bed", "bath": "3 bath", "sqft": "1000-1199 sqft", "age": "New"}
{"street_address": "1016-75 Canterbury Place", "city": "Toronto", "province": "ON", "neighbourhood": "Willowdale West", "price": "879900", "bed": "3 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": "New"}
{"street_address": "2203-100 Harbour Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "659990", "bed": "1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "0-5 Years Old"}
{"street_address": "5682 Sheppard Avenue E", "city": "Toronto", "province": "ON", "neighbourhood": "Malvern", "price": "799000", "bed": "3 bed", "bath": "4 bath", "sqft": null, "age": null}
{"street_address": "22 Trailview Terrace", "city": "Toronto", "province": "ON", "neighbourhood": "Rouge E11", "price": "899000", "bed": "3+1 bed", "bath": "3 bath", "sqft": "1100-1500 sqft", "age": "16-30 Years Old"}
{"street_address": "56 Wolcott Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Oakridge", "price": "1150000", "bed": "3+2 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "61 Collinson Boulevard", "city": "Toronto", "province": "ON", "neighbourhood": "Clanton Park", "price": "1299995", "bed": "3+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "803-2300 St Clair Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Junction Area", "price": "768000", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": "1406-2550 Lawrence Avenue E", "city": "Toronto", "province": "ON", "neighbourhood": "Dorset Park", "price": "599000", "bed": "2 bed", "bath": "2 bath", "sqft": "900-999 sqft", "age": null}
{"street_address": "1806-18 Harbour Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "719000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "11-15 Years Old"}
{"street_address": "1907-2191 Yonge Street", "city": "Toronto", "province": "ON", "neighbourhood": "Mount Pleasant West", "price": "499000", "bed": "1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "3410-87 Peter Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "709000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": null}
{"street_address": "93 Valley Stream Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Milliken", "price": "888000", "bed": "3+2 bed", "bath": "4 bath", "sqft": "1500-2000 sqft", "age": "31-50 Years Old"}
{"street_address": "44 Glengarry Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Lawrence Park North", "price": "1898000", "bed": "3 bed", "bath": "4 bath", "sqft": null, "age": null}
{"street_address": "201-1 Rean Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Bayview Village", "price": "629999", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": "16-30 Years Old"}
{"street_address": "1007-15 Grenville Street", "city": "Toronto", "province": "ON", "neighbourhood": "Bay Street Corridor", "price": "654990", "bed": "1 bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": "6-10 Years Old"}
{"street_address": "322-19 Western Battery Road", "city": "Toronto", "province": "ON", "neighbourhood": "Niagara", "price": "600000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "0-5 Years Old"}
{"street_address": "305-131 Torresdale Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Westminster-Branson", "price": "875000", "bed": "2+2 bed", "bath": "2 bath", "sqft": "1400-1599 sqft", "age": null}
{"street_address": " Hampton Park Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "Leaside", "price": null, "bed": "$X,XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": " Navy Wharf Court", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": null, "bed": "$XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "57 Garthdale Court", "city": "Toronto", "province": "ON", "neighbourhood": "Bathurst Manor", "price": "899888", "bed": "5 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "1704-2285 Lake Shore Boulevard W", "city": "Toronto", "province": "ON", "neighbourhood": "Mimico", "price": "499000", "bed": "1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": "31-50 Years Old"}
{"street_address": "521-293 The Kingsway ", "city": "Toronto", "province": "ON", "neighbourhood": "Edenbridge-Humber Valley", "price": "849000", "bed": "2 bed", "bath": "2 bath", "sqft": "700-799 sqft", "age": "New"}
{"street_address": "511-200 Manitoba Street", "city": "Toronto", "province": "ON", "neighbourhood": "Mimico", "price": "599999", "bed": "1 bed", "bath": "2 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "814-455 Sentinel Road", "city": "Toronto", "province": "ON", "neighbourhood": "York University Heights", "price": "389000", "bed": "1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "105-412 Jarvis Street", "city": "Toronto", "province": "ON", "neighbourhood": "Church-Yonge Corridor", "price": "499000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": null}
{"street_address": "14 Riverdale Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "North Riverdale", "price": "1299000", "bed": "2+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "209-1888 Queen Street E", "city": "Toronto", "province": "ON", "neighbourhood": "The Beaches", "price": "795000", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": "0-5 Years Old"}
{"street_address": "506-71 Front Street E", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C8", "price": "929000", "bed": "2 bed", "bath": "2 bath", "sqft": "1400-1599 sqft", "age": "31-50 Years Old"}
{"street_address": " Lower Jarvis Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C8", "price": null, "bed": "$XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "3009-85 Wood Street", "city": "Toronto", "province": "ON", "neighbourhood": "Church-Yonge Corridor", "price": "719000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "0-5 Years Old"}
{"street_address": "403-68 Yorkville Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Annex", "price": "799000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "450 Valermo Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Alderwood", "price": "1792000", "bed": "3 bed", "bath": "5 bath", "sqft": "2500-3000 sqft", "age": "6-15 Years Old"}
{"street_address": "12 Cosmic Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Banbury-Don Mills", "price": "3999000", "bed": "5+1 bed", "bath": "7 bath", "sqft": null, "age": null}
{"street_address": "139 Beechwood Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Bridle Path-Sunnybrook-York Mills", "price": "5180000", "bed": "4+1 bed", "bath": "6 bath", "sqft": null, "age": null}
{"street_address": "812-383 Sorauren Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Roncesvalles", "price": "685000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": null}
{"street_address": "2307-215 Queen Street E", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "459000", "bed": "– bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": "0-5 Years Old"}
{"street_address": "407-70 Distillery Lane", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C8", "price": "855000", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": " Richmond Street W", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": null, "bed": "$XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "94 Blossom Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "Glenfield-Jane Heights", "price": "899900", "bed": "4+1 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "323-4208 Dundas Street W", "city": "Toronto", "province": "ON", "neighbourhood": "Edenbridge-Humber Valley", "price": "610000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "New"}
{"street_address": "10 Cartwheel Mill Way", "city": "Toronto", "province": "ON", "neighbourhood": "St. Andrew-Windfields", "price": "1367500", "bed": "3 bed", "bath": "3 bath", "sqft": "1400-1599 sqft", "age": null}
{"street_address": "628-1169 Queen Street W", "city": "Toronto", "province": "ON", "neighbourhood": "Little Portugal", "price": "549900", "bed": "1 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": " SE-60 Princess Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C8", "price": null, "bed": "$XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "17 Blakemanor Boulevard", "city": "Toronto", "province": "ON", "neighbourhood": "Woburn", "price": "989999", "bed": "3+2 bed", "bath": "2 bath", "sqft": "1100-1500 sqft", "age": null}
{"street_address": "1806-225 Sherway Gardens Road", "city": "Toronto", "province": "ON", "neighbourhood": "Islington-City Centre West", "price": "599900", "bed": "2 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "202-801 Sheppard Avenue W", "city": "Toronto", "province": "ON", "neighbourhood": "Clanton Park", "price": "499900", "bed": "2 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": "6-10 Years Old"}
{"street_address": "712-1005 King Street W", "city": "Toronto", "province": "ON", "neighbourhood": "Niagara", "price": "699000", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": "16-30 Years Old"}
{"street_address": "128 Rochester Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Bridle Path-Sunnybrook-York Mills", "price": "6388000", "bed": "5+1 bed", "bath": "5 bath", "sqft": "3500-5000 sqft", "age": null}
{"street_address": "1602-20 Shore Breeze Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Mimico", "price": "858000", "bed": "2 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": "0-5 Years Old"}
{"street_address": "30 Calora Court", "city": "Toronto", "province": "ON", "neighbourhood": "L'Amoreaux", "price": "898000", "bed": "3+1 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "96 Painswick Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "Pleasant View", "price": "899900", "bed": "4+1 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "850-30 Tandridge Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "Elms-Old Rexdale", "price": "499900", "bed": "3 bed", "bath": "2 bath", "sqft": "1200-1399 sqft", "age": null}
{"street_address": "101-1195 The Queensway ", "city": "Toronto", "province": "ON", "neighbourhood": "Islington-City Centre West", "price": "465000", "bed": "1 bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": "0-5 Years Old"}
{"street_address": "PH 807-36 Howard Park Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Roncesvalles", "price": "718000", "bed": "2 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "7M-8 Rosebank Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Malvern", "price": "468000", "bed": "2 bed", "bath": "1 bath", "sqft": "600-699 sqft", "age": null}
{"street_address": "606-4101 Sheppard Avenue E", "city": "Toronto", "province": "ON", "neighbourhood": "Agincourt South-Malvern West", "price": "399000", "bed": "2 bed", "bath": "1 bath", "sqft": "1000-1199 sqft", "age": null}
{"street_address": " Alton Towers Circle", "city": "Toronto", "province": "ON", "neighbourhood": "Milliken", "price": null, "bed": "$XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "402-4091 Sheppard Avenue E", "city": "Toronto", "province": "ON", "neighbourhood": "Agincourt South-Malvern West", "price": "539000", "bed": "3 bed", "bath": "2 bath", "sqft": "1200-1399 sqft", "age": null}
{"street_address": "805C-662 Sheppard Avenue E", "city": "Toronto", "province": "ON", "neighbourhood": "Bayview Village", "price": "1795000", "bed": "2 bed", "bath": "3 bath", "sqft": "1800-1999 sqft", "age": null}
{"street_address": "2516-155 Beecroft Road", "city": "Toronto", "province": "ON", "neighbourhood": "Lansing-Westgate", "price": "699000", "bed": "2+1 bed", "bath": "2 bath", "sqft": "900-999 sqft", "age": null}
{"street_address": "515-255 The Donway W", "city": "Toronto", "province": "ON", "neighbourhood": "Banbury-Don Mills", "price": "810000", "bed": "2 bed", "bath": "2 bath", "sqft": "1400-1599 sqft", "age": null}
{"street_address": "1117-320 Richmond Street E", "city": "Toronto", "province": "ON", "neighbourhood": "Moss Park", "price": "519000", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": null}
{"street_address": "3802-318 Richmond Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "885000", "bed": "2 bed", "bath": "1 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": "262 Sammon Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Danforth Village-East York", "price": "899000", "bed": "2 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "5 Penmarric Place", "city": "Toronto", "province": "ON", "neighbourhood": "Milliken", "price": "849999", "bed": "3+1 bed", "bath": "3 bath", "sqft": null, "age": null}
{"street_address": "15 Derwyn Road", "city": "Toronto", "province": "ON", "neighbourhood": "East York", "price": "979000", "bed": "– bed", "bath": "– bath", "sqft": null, "age": null}
{"street_address": "3812-11 Brunel Court", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "750000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "1018-35 Hollywood Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Willowdale East", "price": "839000", "bed": "2 bed", "bath": "2 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "9-1968 Bloor Street W", "city": "Toronto", "province": "ON", "neighbourhood": "High Park North", "price": "1130000", "bed": "2+1 bed", "bath": "3 bath", "sqft": "1100-1500 sqft", "age": "16-30 Years Old"}
{"street_address": " Archwood Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "Wexford-Maryvale", "price": null, "bed": "$XXX,XXX", "bath": "— bed", "sqft": "— bath", "age": "— sqft"}
{"street_address": "507-15 Legion Road", "city": "Toronto", "province": "ON", "neighbourhood": "Mimico", "price": "799000", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": "36 Samba Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Humbermede", "price": "1099000", "bed": "3+2 bed", "bath": "3 bath", "sqft": "1100-1500 sqft", "age": null}
{"street_address": "204-1 Valhalla Inn Road", "city": "Toronto", "province": "ON", "neighbourhood": "Islington-City Centre West", "price": "589000", "bed": "1+1 bed", "bath": "1 bath", "sqft": "700-799 sqft", "age": null}
{"street_address": "413-120 Parliament Street", "city": "Toronto", "province": "ON", "neighbourhood": "Moss Park", "price": "1068000", "bed": "3+1 bed", "bath": "2 bath", "sqft": "1000-1199 sqft", "age": "0-5 Years Old"}
{"street_address": "22 Vancho Crescent", "city": "Toronto", "province": "ON", "neighbourhood": "Edenbridge-Humber Valley", "price": "2399000", "bed": "5+1 bed", "bath": "5 bath", "sqft": "3500-5000 sqft", "age": null}
{"street_address": "519-160 Flemington Road", "city": "Toronto", "province": "ON", "neighbourhood": "Yorkdale-Glen Park", "price": "495000", "bed": "1 bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": null}
{"street_address": "3211-108 Peter Street", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "769000", "bed": "1+1 bed", "bath": "2 bath", "sqft": "600-699 sqft", "age": "0-5 Years Old"}
{"street_address": "159 Silverthorn Avenue", "city": "Toronto", "province": "ON", "neighbourhood": "Weston-Pellam Park", "price": "749900", "bed": "2 bed", "bath": "2 bath", "sqft": null, "age": null}
{"street_address": "2311-15 Iceboat Terrace", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "649900", "bed": "1 bed", "bath": "1 bath", "sqft": "500-599 sqft", "age": "11-15 Years Old"}
{"street_address": "9 Stark Apple Way", "city": "Toronto", "province": "ON", "neighbourhood": "Parkwoods-Donalda", "price": "799000", "bed": "3 bed", "bath": "3 bath", "sqft": "1100-1500 sqft", "age": null}
{"street_address": "3603-115 Blue Jays Way", "city": "Toronto", "province": "ON", "neighbourhood": "Waterfront Communities C1", "price": "499900", "bed": "– bed", "bath": "1 bath", "sqft": "0-499 sqft", "age": "0-5 Years Old"}
{"street_address": "1415 Military Trail", "city": "Toronto", "province": "ON", "neighbourhood": "Highland Creek", "price": "2399000", "bed": "4+1 bed", "bath": "6 bath", "sqft": null, "age": null}
{"street_address": "73 Longsword Drive", "city": "Toronto", "province": "ON", "neighbourhood": "Agincourt North", "price": "899000", "bed": "3+1 bed", "bath": "4 bath", "sqft": null, "age": null}
{"street_address": "3310-275 Yorkland Road", "city": "Toronto", "province": "ON", "neighbourhood": "Henry Farm", "price": "709000", "bed": "2 bed", "bath": "2 bath", "sqft": "800-899 sqft", "age": null}
{"street_address": "37 Kenmanor Boulevard", "city": "Toronto", "province": "ON", "neighbourhood": "L'Amoreaux", "price": "1288800", "bed": "4+1 bed", "bath": "4 bath", "sqft": null, "age": null}
